# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Beering' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Beering
  
  # 통신 라이브러리
  pod 'Alamofire'
  
  # 레이아웃 적용 라이브러리
  pod 'SnapKit'

  # Range Slider 라이브러리
  
end
